# **** This file is made by ../tools/make_depend.php. DO NOT MODIFY ! ****

# text
game/text/clear1.h: game/text/clear1.txt
game/text/clear2.h: game/text/clear2.txt
game/text/clear3.h: game/text/clear3.txt
game/text/clear4.h: game/text/clear4.txt
game/text/clear5.h: game/text/clear5.txt
game/text/clear6.h: game/text/clear6.txt
game/text/clear7.h: game/text/clear7.txt
game/text/clear8.h: game/text/clear8.txt
game/text/continue.h: game/text/continue.txt
game/text/ending1.h: game/text/ending1.txt
game/text/ending2.h: game/text/ending2.txt
game/text/ending3.h: game/text/ending3.txt
game/text/ending4.h: game/text/ending4.txt
game/text/ending5.h: game/text/ending5.txt
game/text/ending6.h: game/text/ending6.txt
game/text/ending6_continue.h: game/text/ending6_continue.txt
game/text/ending6_enemies.h: game/text/ending6_enemies.txt
game/text/ending6_items.h: game/text/ending6_items.txt
game/text/ending6_miss.h: game/text/ending6_miss.txt
game/text/ending6_survive_time.h: game/text/ending6_survive_time.txt
game/text/finish.h: game/text/finish.txt
game/text/game_end.h: game/text/game_end.txt
game/text/game_mode.h: game/text/game_mode.txt
game/text/game_mode_back.h: game/text/game_mode_back.txt
game/text/game_mode_caravan.h: game/text/game_mode_caravan.txt
game/text/game_mode_easy.h: game/text/game_mode_easy.txt
game/text/game_mode_hard.h: game/text/game_mode_hard.txt
game/text/game_mode_mubo.h: game/text/game_mode_mubo.txt
game/text/game_mode_mz1x03_insensitivity.h: game/text/game_mode_mz1x03_insensitivity.txt
game/text/game_mode_normal.h: game/text/game_mode_normal.txt
game/text/game_mode_survival.h: game/text/game_mode_survival.txt
game/text/game_over.h: game/text/game_over.txt
game/text/game_results.h: game/text/game_results.txt
game/text/input_am7j.h: game/text/input_am7j.txt
game/text/input_mz1x03.h: game/text/input_mz1x03.txt
game/text/key_assign.h: game/text/key_assign.txt
game/text/key_cancel.h: game/text/key_cancel.txt
game/text/key_joy.h: game/text/key_joy.txt
game/text/key_move.h: game/text/key_move.txt
game/text/key_shot.h: game/text/key_shot.txt
game/text/key_start.h: game/text/key_start.txt
game/text/nwk_presents.h: game/text/nwk_presents.txt
game/text/opening.h: game/text/opening.txt
game/text/tab100.h: game/text/tab100.txt
game/text/tab150.h: game/text/tab150.txt
game/text/tab200.h: game/text/tab200.txt
game/text/tab250.h: game/text/tab250.txt
game/text/tab300.h: game/text/tab300.txt
game/text/tab400.h: game/text/tab400.txt
game/text/tab_level_up.h: game/text/tab_level_up.txt
game/text/tab_score.h: game/text/tab_score.txt
game/text/title_bonus.h: game/text/title_bonus.txt
game/text/title_comma.h: game/text/title_comma.txt
game/text/title_pts.h: game/text/title_pts.txt
game/text/title_snail.h: game/text/title_snail.txt
game/text/title_start.h: game/text/title_start.txt
