# **** This file is made by ../tools/make-depend.php. DO NOT MODIFY ! ****

# text
game/text/clear1.h: game/text/clear1.txt
game/text/clear2.h: game/text/clear2.txt
game/text/clear3.h: game/text/clear3.txt
game/text/clear4.h: game/text/clear4.txt
game/text/clear5.h: game/text/clear5.txt
game/text/clear6.h: game/text/clear6.txt
game/text/clear7.h: game/text/clear7.txt
game/text/clear8.h: game/text/clear8.txt
game/text/continue.h: game/text/continue.txt
game/text/ending1.h: game/text/ending1.txt
game/text/ending2.h: game/text/ending2.txt
game/text/ending3.h: game/text/ending3.txt
game/text/ending4.h: game/text/ending4.txt
game/text/ending5.h: game/text/ending5.txt
game/text/ending6-continue.h: game/text/ending6-continue.txt
game/text/ending6-enemies.h: game/text/ending6-enemies.txt
game/text/ending6-items.h: game/text/ending6-items.txt
game/text/ending6-miss.h: game/text/ending6-miss.txt
game/text/ending6-survive-time.h: game/text/ending6-survive-time.txt
game/text/ending6.h: game/text/ending6.txt
game/text/finish.h: game/text/finish.txt
game/text/game-end.h: game/text/game-end.txt
game/text/game-mode-back.h: game/text/game-mode-back.txt
game/text/game-mode-caravan.h: game/text/game-mode-caravan.txt
game/text/game-mode-easy.h: game/text/game-mode-easy.txt
game/text/game-mode-hard.h: game/text/game-mode-hard.txt
game/text/game-mode-mubo.h: game/text/game-mode-mubo.txt
game/text/game-mode-mz1x03-sensitivity.h: game/text/game-mode-mz1x03-sensitivity.txt
game/text/game-mode-normal.h: game/text/game-mode-normal.txt
game/text/game-mode-survival.h: game/text/game-mode-survival.txt
game/text/game-mode.h: game/text/game-mode.txt
game/text/game-over.h: game/text/game-over.txt
game/text/game-results.h: game/text/game-results.txt
game/text/input-am7j.h: game/text/input-am7j.txt
game/text/input-mz1x03.h: game/text/input-mz1x03.txt
game/text/joymode-auto-detect.h: game/text/joymode-auto-detect.txt
game/text/joymode-mz1x03.h: game/text/joymode-mz1x03.txt
game/text/joymode.h: game/text/joymode.txt
game/text/key-assign.h: game/text/key-assign.txt
game/text/key-cancel.h: game/text/key-cancel.txt
game/text/key-joy.h: game/text/key-joy.txt
game/text/key-move.h: game/text/key-move.txt
game/text/key-shot.h: game/text/key-shot.txt
game/text/key-start.h: game/text/key-start.txt
game/text/nwk-presents.h: game/text/nwk-presents.txt
game/text/opening.h: game/text/opening.txt
game/text/tab-level-up.h: game/text/tab-level-up.txt
game/text/tab-score.h: game/text/tab-score.txt
game/text/tab100.h: game/text/tab100.txt
game/text/tab150.h: game/text/tab150.txt
game/text/tab200.h: game/text/tab200.txt
game/text/tab250.h: game/text/tab250.txt
game/text/tab300.h: game/text/tab300.txt
game/text/tab400.h: game/text/tab400.txt
game/text/title-bonus.h: game/text/title-bonus.txt
game/text/title-comma.h: game/text/title-comma.txt
game/text/title-pts.h: game/text/title-pts.txt
game/text/title-snail.h: game/text/title-snail.txt
game/text/title-start.h: game/text/title-start.txt
