# **** This file is made by ../tools/make-depend.php. DO NOT MODIFY ! ****

# prog
game/src/scenes/scene-ending.o: game/src/scenes/scene-ending.c ../src-common/common.h ../src-common/hard.h game/src/system/sys.h game/src/system/sound.h game/src/system/print.h ../src-common/display-code.h game/src/system/vvram.h game/src/system/addr.h game/src/system/math.h game/src/game/score.h game/src/game/stage.h game/src/game/se.h game/src/game/game-mode.h game/src/game/stars.h game/src/objworks/obj-player.h game/src/system/obj.h game/src/objworks/obj-enemy.h game/src/objworks/obj-item.h game/src/scenes/scene-logo.h game/src/scenes/scene-game-mode.h game/src/scenes/scene-ending.h game/music/ending-bar8.h game/text/ending1.h game/text/ending2.h game/text/ending3.h game/text/ending4.h game/text/ending5.h game/text/ending6.h game/text/finish.h game/text/game-results.h game/text/ending6-continue.h game/text/ending6-miss.h game/text/ending6-items.h game/text/ending6-enemies.h game/text/ending6-survive-time.h
game/src/scenes/scene-game-mode.o: game/src/scenes/scene-game-mode.c ../src-common/common.h ../src-common/hard.h game/src/system/sys.h game/src/system/sound.h game/src/system/vvram.h game/src/system/addr.h game/src/system/print.h ../src-common/display-code.h game/src/system/input.h game/src/game/score.h game/src/game/se.h game/src/game/game-mode.h game/src/scenes/scene-logo.h game/src/scenes/scene-opening.h game/src/scenes/scene-game-mode.h game/text/game-mode-easy.h game/text/game-mode-normal.h game/text/game-mode-hard.h game/text/game-mode-survival.h game/text/game-mode-mubo.h game/text/game-mode-caravan.h game/text/joymode.h game/text/joymode-auto-detect.h game/text/joymode-mz1x03.h game/text/game-mode-mz1x03-sensitivity.h game/text/game-mode-back.h game/text/game-mode.h
game/src/scenes/scene-game-over.o: game/src/scenes/scene-game-over.c game/src/system/sys.h ../src-common/common.h game/src/system/sound.h game/src/system/print.h ../src-common/display-code.h game/src/system/obj.h game/src/game/score.h game/src/game/stage.h game/src/game/bgm.h game/src/scenes/scene-logo.h game/src/scenes/scene-game-over.h game/music/ronin.h
game/src/scenes/scene-game.o: game/src/scenes/scene-game.c ../src-common/common.h ../src-common/hard.h game/src/system/sys.h game/src/system/addr.h game/src/system/input.h game/src/system/vvram.h game/src/system/print.h ../src-common/display-code.h game/src/system/sound.h game/src/system/obj.h game/src/system/math.h game/src/game/score.h game/src/game/game-mode.h game/src/game/stage.h game/src/objworks/obj-player.h game/cg/Pause.h game/src/scenes/scene-stage-clear.h game/src/scenes/scene-ending.h game/src/scenes/scene-score-table.h game/src/scenes/scene-game-over.h game/src/scenes/scene-game.h
game/src/scenes/scene-instruction.o: game/src/scenes/scene-instruction.c ../src-common/common.h game/src/system/addr.h game/src/system/sys.h game/src/system/vvram.h game/src/system/print.h ../src-common/display-code.h game/src/system/obj.h game/src/game/score.h game/src/objworks/obj-player.h game/src/objworks/obj-player-bullet.h game/src/objworks/obj-enemy.h game/src/scenes/scene-game.h game/src/scenes/scene-instruction.h game/text/key-assign.h game/text/key-move.h game/text/key-shot.h game/text/key-joy.h game/text/key-start.h game/text/key-cancel.h
game/src/scenes/scene-logo.o: game/src/scenes/scene-logo.c ../src-common/common.h ../src-common/hard.h game/src/system/addr.h game/src/system/sys.h game/src/system/vvram.h game/src/system/print.h ../src-common/display-code.h game/src/system/sound.h game/src/system/obj.h game/src/game/stars.h game/src/game/score.h game/src/game/game-mode.h game/src/scenes/scene-title-demo.h game/src/scenes/scene-logo.h
game/src/scenes/scene-opening.o: game/src/scenes/scene-opening.c game/src/system/sys.h ../src-common/common.h game/src/system/sound.h game/src/system/vvram.h game/src/system/addr.h game/src/system/print.h ../src-common/display-code.h game/src/system/obj.h game/src/game/score.h game/src/game/stage.h game/src/objworks/obj-player.h game/src/scenes/scene-game.h game/src/scenes/scene-opening.h game/text/opening.h game/music/opening.h
game/src/scenes/scene-score-table.o: game/src/scenes/scene-score-table.c ../src-common/common.h ../src-common/hard.h game/src/system/addr.h game/src/system/sys.h game/src/system/vvram.h game/src/system/print.h ../src-common/display-code.h game/src/system/obj.h game/src/game/score.h game/src/objworks/obj-enemy.h game/src/scenes/scene-logo.h game/src/scenes/scene-title-demo.h game/src/scenes/scene-score-table.h game/text/tab-score.h game/text/tab100.h game/text/tab150.h game/text/tab200.h game/text/tab250.h game/text/tab300.h game/text/tab400.h game/text/tab-level-up.h
game/src/scenes/scene-stage-clear.o: game/src/scenes/scene-stage-clear.c ../src-common/common.h ../src-common/hard.h game/src/system/addr.h game/src/system/sys.h game/src/system/vvram.h game/src/system/print.h ../src-common/display-code.h game/src/system/sound.h game/src/game/score.h game/src/game/stage.h game/src/scenes/scene-game.h game/src/scenes/scene-stage-clear.h game/text/clear1.h game/text/clear2.h game/text/clear3.h game/text/clear4.h game/text/clear5.h game/text/clear6.h game/text/clear7.h game/text/clear8.h game/music/clear.h
game/src/scenes/scene-title-demo.o: game/src/scenes/scene-title-demo.c ../src-common/common.h game/src/system/addr.h game/src/system/sys.h game/src/system/input.h game/src/system/vvram.h game/src/system/print.h ../src-common/display-code.h game/src/system/math.h game/src/system/obj.h game/src/game/score.h game/src/scenes/scene-title.h game/src/scenes/scene-title-demo.h
game/src/scenes/scene-title.o: game/src/scenes/scene-title.c ../src-common/common.h game/src/system/addr.h game/src/system/sys.h game/src/system/version.h game/src/system/input.h game/src/system/vvram.h game/src/system/print.h ../src-common/display-code.h game/src/system/math.h game/src/system/sound.h game/src/system/obj.h game/src/game/se.h game/src/game/score.h game/src/game/stage.h game/src/scenes/scene-instruction.h game/src/scenes/scene-game-mode.h game/src/scenes/scene-title-demo.h game/src/scenes/scene-title.h game/text/title-snail.h game/text/title-start.h game/text/title-bonus.h game/text/title-comma.h game/text/title-pts.h game/text/nwk-presents.h game/cg/title-s.h game/cg/title-t.h game/cg/title-hyphen.h game/cg/title-2.h
GAME_SCENES_OBJS := game/src/scenes/scene-ending.o game/src/scenes/scene-game-mode.o game/src/scenes/scene-game-over.o game/src/scenes/scene-game.o game/src/scenes/scene-instruction.o game/src/scenes/scene-logo.o game/src/scenes/scene-opening.o game/src/scenes/scene-score-table.o game/src/scenes/scene-stage-clear.o game/src/scenes/scene-title-demo.o game/src/scenes/scene-title.o
GAME_SCENES_CLEAN_FILES := game/src/scenes/scene-ending.o game/src/scenes/scene-game-mode.o game/src/scenes/scene-game-over.o game/src/scenes/scene-game.o game/src/scenes/scene-instruction.o game/src/scenes/scene-logo.o game/src/scenes/scene-opening.o game/src/scenes/scene-score-table.o game/src/scenes/scene-stage-clear.o game/src/scenes/scene-title-demo.o game/src/scenes/scene-title.o
