# **** This file is made by ../tools/make-depend.php. DO NOT MODIFY ! ****

# prog
game/src/objworks/obj-enemy-bullet.o: game/src/objworks/obj-enemy-bullet.c ../src-common/common.h game/src/system/addr.h game/src/system/obj.h game/src/system/vvram.h game/src/system/sound.h game/src/system/math.h game/src/objworks/obj-player.h game/src/objworks/obj-enemy-bullet.h
game/src/objworks/obj-enemy.o: game/src/objworks/obj-enemy.c ../src-common/common.h game/src/system/sys.h game/src/system/obj.h game/src/system/vvram.h game/src/system/addr.h game/src/system/print.h ../src-common/display-code.h game/src/system/sound.h game/src/system/math.h game/src/game/score.h game/src/game/stage.h game/src/game/game-mode.h game/src/game/se.h game/cg/enemy3-1.h game/cg/enemy3-2.h game/cg/enemy3-3.h game/cg/enemy3-4.h game/cg/enemy3-5.h game/cg/enemy3-6.h game/cg/enemy4-1.h game/cg/enemy4-2.h game/cg/enemy4-3.h game/cg/enemy5-1.h game/cg/enemy5-2.h game/cg/enemy5-3.h game/cg/enemy8-1.h game/cg/enemy-damage3.h game/cg/enemy-damage3-6.h game/cg/enemy-damage4.h game/cg/enemy-damage5.h game/cg/enemy-damage8.h game/cg/enemy-red8.h game/src/objworks/obj-item.h game/src/objworks/obj-player.h game/src/objworks/obj-explosion.h game/src/objworks/obj-enemy-bullet.h game/src/objworks/obj-score.h game/src/objworks/obj-enemy.h
game/src/objworks/obj-explosion.o: game/src/objworks/obj-explosion.c ../src-common/common.h game/src/system/obj.h game/src/system/vvram.h game/src/system/addr.h game/src/system/sound.h game/src/system/math.h game/cg/explosion0.h game/cg/explosion1.h game/cg/explosion2.h game/cg/explosion3.h game/cg/explosion4.h game/cg/explosion5.h game/cg/explosion6.h game/cg/explosion7.h game/src/objworks/obj-player-bullet.h
game/src/objworks/obj-item.o: game/src/objworks/obj-item.c ../src-common/common.h game/src/system/addr.h game/src/system/obj.h game/src/system/vvram.h game/src/system/print.h ../src-common/display-code.h game/src/system/sound.h game/src/system/math.h game/src/game/score.h game/src/game/se.h game/src/game/game-mode.h game/src/objworks/obj-item.h
game/src/objworks/obj-player-bullet.o: game/src/objworks/obj-player-bullet.c ../src-common/common.h game/src/system/addr.h game/src/system/obj.h game/src/system/vvram.h game/src/system/sound.h game/src/game/score.h game/src/objworks/obj-player-bullet.h
game/src/objworks/obj-player.o: game/src/objworks/obj-player.c ../src-common/common.h ../src-common/hard.h game/src/system/addr.h game/src/system/sys.h game/src/system/input.h game/src/system/obj.h game/src/system/vvram.h game/src/system/print.h ../src-common/display-code.h game/src/system/sound.h game/src/system/math.h game/src/game/score.h game/src/game/stage.h game/src/game/game-mode.h game/src/game/se.h game/cg/player.h game/cg/nr0.h game/cg/nr1.h game/cg/nr2.h game/cg/nr3.h game/cg/nr4.h game/cg/nr5.h game/cg/nr6.h game/cg/nr7.h game/src/scenes/scene-game-mode.h game/src/scenes/scene-ending.h game/src/objworks/obj-explosion.h game/src/objworks/obj-player-bullet.h game/src/objworks/obj-player.h game/text/continue.h game/text/finish.h game/text/game-end.h game/music/end.h
game/src/objworks/obj-score.o: game/src/objworks/obj-score.c ../src-common/common.h ../src-common/hard.h game/src/system/obj.h game/src/system/vvram.h game/src/system/addr.h game/src/system/print.h ../src-common/display-code.h game/src/objworks/obj-score.h
GAME_OBJWORKS_OBJS := game/src/objworks/obj-enemy-bullet.o game/src/objworks/obj-enemy.o game/src/objworks/obj-explosion.o game/src/objworks/obj-item.o game/src/objworks/obj-player-bullet.o game/src/objworks/obj-player.o game/src/objworks/obj-score.o
GAME_OBJWORKS_CLEAN_FILES := game/src/objworks/obj-enemy-bullet.o game/src/objworks/obj-enemy.o game/src/objworks/obj-explosion.o game/src/objworks/obj-item.o game/src/objworks/obj-player-bullet.o game/src/objworks/obj-player.o game/src/objworks/obj-score.o
