# **** This file is made by ../tools/make_depend.php. DO NOT MODIFY ! ****

# prog
game/obj/bgm.o: game/src/game/bgm.c ../src-common/common.h game/src/system/obj.h game/src/system/sound.h game/src/system/math.h game/src/objworks/obj_player.h game/src/game/stage.h game/src/game/bgm.h
game/obj/game_mode.o: game/src/game/game_mode.c ../src-common/common.h game/src/system/vram.h game/src/system/addr.h game/src/system/sound.h game/src/game/se.h game/src/game/game_mode.h
game/obj/score.o: game/src/game/score.c ../src-common/common.h ../src-common/hard.h game/src/system/addr.h game/src/system/sys.h game/src/system/vram.h game/src/system/sound.h game/src/system/math.h game/src/system/print.h ../src-common/display_code.h game/src/system/input.h game/src/game/game_mode.h game/src/objworks/obj_item.h game/src/system/obj.h game/src/objworks/obj_enemy.h game/src/game/se.h game/src/game/score.h game/text/game_over.h game/text/input_am7j.h game/text/input_mz1x03.h
game/obj/se.o: game/src/game/se.c ../src-common/common.h game/src/system/sound.h game/src/system/math.h game/src/game/se.h
game/obj/stage.o: game/src/game/stage.c game/src/system/sys.h ../src-common/common.h game/src/system/sound.h game/src/system/math.h game/src/objworks/obj_enemy.h game/src/system/obj.h game/src/objworks/obj_player.h game/src/game/bgm.h game/src/game/se.h game/src/game/game_mode.h game/src/game/stage.h
game/obj/stars.o: game/src/game/stars.c ../src-common/common.h game/src/system/sys.h game/src/system/addr.h game/src/system/obj.h game/src/system/vram.h game/src/system/print.h ../src-common/display_code.h game/src/system/math.h game/src/game/stars.h
game/obj/main.o: game/src/main.c ../src-common/common.h game/src/system/sys.h game/src/system/input.h game/src/system/vram.h game/src/system/addr.h game/src/system/print.h ../src-common/display_code.h game/src/system/sound.h game/src/system/obj.h game/src/system/math.h game/src/scenes/scene_logo.h game/src/game/stars.h game/src/game/score.h game/src/game/game_mode.h game/src/objworks/obj_item.h
game/obj/obj_enemy.o: game/src/objworks/obj_enemy.c ../src-common/common.h game/src/system/sys.h game/src/system/obj.h game/src/system/vram.h game/src/system/addr.h game/src/system/print.h ../src-common/display_code.h game/src/system/sound.h game/src/system/math.h game/src/game/score.h game/src/game/stage.h game/src/game/game_mode.h game/src/game/se.h game/cg/enemy3_1.h game/cg/enemy3_2.h game/cg/enemy3_3.h game/cg/enemy3_4.h game/cg/enemy3_5.h game/cg/enemy3_6.h game/cg/enemy4_1.h game/cg/enemy4_2.h game/cg/enemy4_3.h game/cg/enemy5_1.h game/cg/enemy5_2.h game/cg/enemy5_3.h game/cg/enemy8_1.h game/cg/enemy_damage3.h game/cg/enemy_damage3_6.h game/cg/enemy_damage4.h game/cg/enemy_damage5.h game/cg/enemy_damage8.h game/cg/enemy_red8.h game/src/objworks/obj_item.h game/src/objworks/obj_player.h game/src/objworks/obj_explosion.h game/src/objworks/obj_enemy_bullet.h game/src/objworks/obj_score.h game/src/objworks/obj_enemy.h
game/obj/obj_enemy_bullet.o: game/src/objworks/obj_enemy_bullet.c ../src-common/common.h game/src/system/addr.h game/src/system/obj.h game/src/system/vram.h game/src/system/sound.h game/src/system/math.h game/src/objworks/obj_player.h game/src/objworks/obj_enemy_bullet.h
game/obj/obj_explosion.o: game/src/objworks/obj_explosion.c ../src-common/common.h game/src/system/obj.h game/src/system/vram.h game/src/system/addr.h game/src/system/sound.h game/src/system/math.h game/cg/explosion0.h game/cg/explosion1.h game/cg/explosion2.h game/cg/explosion3.h game/cg/explosion4.h game/cg/explosion5.h game/cg/explosion6.h game/cg/explosion7.h game/src/objworks/obj_player_bullet.h
game/obj/obj_item.o: game/src/objworks/obj_item.c ../src-common/common.h game/src/system/addr.h game/src/system/obj.h game/src/system/vram.h game/src/system/print.h ../src-common/display_code.h game/src/system/sound.h game/src/system/math.h game/src/game/score.h game/src/game/se.h game/src/game/game_mode.h game/src/objworks/obj_item.h
game/obj/obj_player.o: game/src/objworks/obj_player.c ../src-common/common.h ../src-common/hard.h game/src/system/addr.h game/src/system/sys.h game/src/system/input.h game/src/system/obj.h game/src/system/vram.h game/src/system/print.h ../src-common/display_code.h game/src/system/sound.h game/src/system/math.h game/src/game/score.h game/src/game/stage.h game/src/game/game_mode.h game/src/game/se.h game/cg/player.h game/cg/nr0.h game/cg/nr1.h game/cg/nr2.h game/cg/nr3.h game/cg/nr4.h game/cg/nr5.h game/cg/nr6.h game/cg/nr7.h game/src/scenes/scene_game_mode.h game/src/scenes/scene_ending.h game/src/objworks/obj_explosion.h game/src/objworks/obj_player_bullet.h game/src/objworks/obj_player.h game/text/continue.h game/text/finish.h game/text/game_end.h game/music/end.h
game/obj/obj_player_bullet.o: game/src/objworks/obj_player_bullet.c ../src-common/common.h game/src/system/addr.h game/src/system/obj.h game/src/system/vram.h game/src/system/sound.h game/src/game/score.h game/src/objworks/obj_player_bullet.h
game/obj/obj_score.o: game/src/objworks/obj_score.c ../src-common/common.h ../src-common/hard.h game/src/system/obj.h game/src/system/vram.h game/src/system/addr.h game/src/system/print.h ../src-common/display_code.h game/src/objworks/obj_score.h
game/obj/scene_ending.o: game/src/scenes/scene_ending.c ../src-common/common.h ../src-common/hard.h game/src/system/sys.h game/src/system/sound.h game/src/system/print.h ../src-common/display_code.h game/src/system/vram.h game/src/system/addr.h game/src/system/math.h game/src/game/score.h game/src/game/stage.h game/src/game/se.h game/src/game/game_mode.h game/src/game/stars.h game/src/objworks/obj_player.h game/src/system/obj.h game/src/objworks/obj_enemy.h game/src/objworks/obj_item.h game/src/scenes/scene_logo.h game/src/scenes/scene_game_mode.h game/src/scenes/scene_ending.h game/music/ending_bar8.h game/text/ending1.h game/text/ending2.h game/text/ending3.h game/text/ending4.h game/text/ending5.h game/text/ending6.h game/text/finish.h game/text/game_results.h game/text/ending6_continue.h game/text/ending6_miss.h game/text/ending6_items.h game/text/ending6_enemies.h
game/obj/scene_game.o: game/src/scenes/scene_game.c ../src-common/common.h ../src-common/hard.h game/src/system/sys.h game/src/system/addr.h game/src/system/input.h game/src/system/vram.h game/src/system/print.h ../src-common/display_code.h game/src/system/sound.h game/src/system/obj.h game/src/system/math.h game/src/game/score.h game/src/game/game_mode.h game/src/game/stage.h game/src/objworks/obj_player.h game/cg/Pause.h game/src/scenes/scene_stage_clear.h game/src/scenes/scene_ending.h game/src/scenes/scene_score_table.h game/src/scenes/scene_game_over.h game/src/scenes/scene_game.h
game/obj/scene_game_mode.o: game/src/scenes/scene_game_mode.c ../src-common/common.h ../src-common/hard.h game/src/system/sys.h game/src/system/sound.h game/src/system/vram.h game/src/system/addr.h game/src/system/print.h ../src-common/display_code.h game/src/system/input.h game/src/game/score.h game/src/game/se.h game/src/game/game_mode.h game/src/scenes/scene_logo.h game/src/scenes/scene_opening.h game/src/scenes/scene_game_mode.h game/text/game_mode_easy.h game/text/game_mode_normal.h game/text/game_mode_hard.h game/text/game_mode_survival.h game/text/game_mode_mubo.h game/text/game_mode_caravan.h game/text/game_mode_mz1x03_insensitivity.h game/text/game_mode_back.h game/text/game_mode.h
game/obj/scene_game_over.o: game/src/scenes/scene_game_over.c game/src/system/sys.h ../src-common/common.h game/src/system/sound.h game/src/system/print.h ../src-common/display_code.h game/src/system/obj.h game/src/game/score.h game/src/game/stage.h game/src/game/bgm.h game/src/scenes/scene_logo.h game/src/scenes/scene_game_over.h game/music/ronin.h
game/obj/scene_instruction.o: game/src/scenes/scene_instruction.c ../src-common/common.h game/src/system/addr.h game/src/system/sys.h game/src/system/vram.h game/src/system/print.h ../src-common/display_code.h game/src/system/obj.h game/src/game/score.h game/src/objworks/obj_player.h game/src/objworks/obj_player_bullet.h game/src/objworks/obj_enemy.h game/src/scenes/scene_game.h game/src/scenes/scene_instruction.h game/text/key_assign.h game/text/key_move.h game/text/key_shot.h game/text/key_joy.h game/text/key_start.h game/text/key_cancel.h
game/obj/scene_logo.o: game/src/scenes/scene_logo.c ../src-common/common.h ../src-common/hard.h game/src/system/addr.h game/src/system/sys.h game/src/system/vram.h game/src/system/print.h ../src-common/display_code.h game/src/system/sound.h game/src/system/obj.h game/src/game/stars.h game/src/game/score.h game/src/game/game_mode.h game/src/scenes/scene_title_demo.h game/src/scenes/scene_logo.h
game/obj/scene_opening.o: game/src/scenes/scene_opening.c game/src/system/sys.h ../src-common/common.h game/src/system/sound.h game/src/system/vram.h game/src/system/addr.h game/src/system/print.h ../src-common/display_code.h game/src/system/obj.h game/src/game/score.h game/src/game/stage.h game/src/objworks/obj_player.h game/src/scenes/scene_game.h game/src/scenes/scene_opening.h game/text/opening.h game/music/opening.h
game/obj/scene_score_table.o: game/src/scenes/scene_score_table.c ../src-common/common.h ../src-common/hard.h game/src/system/addr.h game/src/system/sys.h game/src/system/vram.h game/src/system/print.h ../src-common/display_code.h game/src/system/obj.h game/src/game/score.h game/src/objworks/obj_enemy.h game/src/scenes/scene_logo.h game/src/scenes/scene_title_demo.h game/src/scenes/scene_score_table.h game/text/tab_score.h game/text/tab100.h game/text/tab150.h game/text/tab200.h game/text/tab250.h game/text/tab300.h game/text/tab400.h game/text/tab_level_up.h
game/obj/scene_stage_clear.o: game/src/scenes/scene_stage_clear.c ../src-common/common.h ../src-common/hard.h game/src/system/addr.h game/src/system/sys.h game/src/system/vram.h game/src/system/print.h ../src-common/display_code.h game/src/system/sound.h game/src/game/score.h game/src/game/stage.h game/src/scenes/scene_game.h game/src/scenes/scene_stage_clear.h game/text/clear1.h game/text/clear2.h game/text/clear3.h game/text/clear4.h game/text/clear5.h game/text/clear6.h game/text/clear7.h game/text/clear8.h game/music/clear.h
game/obj/scene_title.o: game/src/scenes/scene_title.c ../src-common/common.h game/src/system/addr.h game/src/system/sys.h game/src/system/version.h game/src/system/input.h game/src/system/vram.h game/src/system/print.h ../src-common/display_code.h game/src/system/math.h game/src/system/sound.h game/src/system/obj.h game/src/game/se.h game/src/game/score.h game/src/game/stage.h game/src/scenes/scene_instruction.h game/src/scenes/scene_game_mode.h game/src/scenes/scene_title_demo.h game/src/scenes/scene_title.h game/text/title_snail.h game/text/title_start.h game/text/title_bonus.h game/text/title_comma.h game/text/title_pts.h game/text/nwk_presents.h game/cg/title_s.h game/cg/title_t.h game/cg/title_hyphen.h game/cg/title_2.h
game/obj/scene_title_demo.o: game/src/scenes/scene_title_demo.c ../src-common/common.h game/src/system/addr.h game/src/system/sys.h game/src/system/input.h game/src/system/vram.h game/src/system/print.h ../src-common/display_code.h game/src/system/math.h game/src/system/obj.h game/src/game/score.h game/src/scenes/scene_title.h game/src/scenes/scene_title_demo.h
game/obj/assert.o: game/src/system/assert.c game/src/system/assert.h ../src-common/common.h ../src-common/hard.h ../src-common/display_code.h
game/obj/input.o: game/src/system/input.c ../src-common/common.h ../src-common/hard.h game/src/system/assert.h game/src/system/input.h
game/obj/math.o: game/src/system/math.c ../src-common/common.h game/src/system/addr.h game/src/system/math.h
game/obj/obj.o: game/src/system/obj.c ../src-common/common.h game/src/system/addr.h game/src/system/obj.h game/src/system/vram.h game/src/system/sound.h
game/obj/print.o: game/src/system/print.c ../src-common/common.h game/src/system/addr.h game/src/system/sys.h game/src/system/vram.h game/src/system/print.h ../src-common/display_code.h
game/obj/sound.o: game/src/system/sound.c ../src-common/common.h ../src-common/hard.h game/src/system/addr.h game/src/system/vram.h game/src/system/math.h game/src/game/bgm.h game/src/game/se.h game/src/system/sound.h
game/obj/sys.o: game/src/system/sys.c ../src-common/common.h game/src/system/addr.h game/src/system/sound.h game/src/system/input.h game/src/system/vram.h game/src/system/sys.h game/src/game/bgm.h game/src/scenes/scene_title.h
game/obj/utils.o: game/src/system/utils.c ../src-common/common.h game/src/system/utils.h
game/obj/vram.o: game/src/system/vram.c ../src-common/common.h ../src-common/hard.h game/src/system/addr.h game/src/system/input.h game/src/system/vram.h game/src/system/math.h
GAME_OBJS := game/obj/bgm.o game/obj/game_mode.o game/obj/score.o game/obj/se.o game/obj/stage.o game/obj/stars.o game/obj/main.o game/obj/obj_enemy.o game/obj/obj_enemy_bullet.o game/obj/obj_explosion.o game/obj/obj_item.o game/obj/obj_player.o game/obj/obj_player_bullet.o game/obj/obj_score.o game/obj/scene_ending.o game/obj/scene_game.o game/obj/scene_game_mode.o game/obj/scene_game_over.o game/obj/scene_instruction.o game/obj/scene_logo.o game/obj/scene_opening.o game/obj/scene_score_table.o game/obj/scene_stage_clear.o game/obj/scene_title.o game/obj/scene_title_demo.o game/obj/assert.o game/obj/input.o game/obj/math.o game/obj/obj.o game/obj/print.o game/obj/sound.o game/obj/sys.o game/obj/utils.o game/obj/vram.o
GAME_CLEAN_FILES := game/obj/bgm.o game/obj/game_mode.o game/obj/score.o game/obj/se.o game/obj/stage.o game/obj/stars.o game/obj/main.o game/obj/obj_enemy.o game/obj/obj_enemy_bullet.o game/obj/obj_explosion.o game/obj/obj_item.o game/obj/obj_player.o game/obj/obj_player_bullet.o game/obj/obj_score.o game/obj/scene_ending.o game/obj/scene_game.o game/obj/scene_game_mode.o game/obj/scene_game_over.o game/obj/scene_instruction.o game/obj/scene_logo.o game/obj/scene_opening.o game/obj/scene_score_table.o game/obj/scene_stage_clear.o game/obj/scene_title.o game/obj/scene_title_demo.o game/obj/assert.o game/obj/input.o game/obj/math.o game/obj/obj.o game/obj/print.o game/obj/sound.o game/obj/sys.o game/obj/utils.o game/obj/vram.o
