/**** This file is made by ../tools/sd6-midi-conv.php. DO NOT MODIFY! ****/
// Lead 音階ヒストグラム(計453):
//   A#3 x 12
//   A#4 x 4
//   A3  x 38
//   A4  x 11
//   B2  x 1
//   B3  x 67
//   B4  x 9
//   C#3 x 4
//   C#4 x 60
//   C#5 x 2
//   C4  x 1
//   D#4 x 16
//   D4  x 40
//   E3  x 10
//   E4  x 38
//   F#3 x 67
//   F#4 x 43
//   F4  x 2
//   G#3 x 3
//   G#4 x 25
// Base 音階ヒストグラム(計605):
//   A#2 x 1
//   A#3 x 1
//   A2  x 119
//   A3  x 1
//   B1  x 74
//   B2  x 153
//   B3  x 1
//   C#2 x 1
//   C#4 x 1
//   C4  x 1
//   D#3 x 1
//   D#4 x 1
//   D2  x 21
//   E2  x 85
//   F#2 x 120
//   F#3 x 2
//   F3  x 1
//   G#2 x 19
//   G#3 x 2
// Chord0/1 音階ヒストグラム(計276):
//   A#2 x 1
//   A3  x 24
//   B2  x 4
//   B3  x 24
//   C#3 x 7
//   C3  x 2
//   D#3 x 25
//   D3  x 37
//   E3  x 58
//   F#3 x 55
//   F3  x 5
//   G#3 x 32
//   R   x 2
// Drum 音階ヒストグラム(計391):
//   B1  x 222
//   C#2 x 33
//   C2  x 133
//   R   x 3
// 音符 計1725
// 音長ヒストグラム(計1587):
//   4 x 47
//   8 x 885
//   16 x 246
//   24 x 60
//   32 x 222
//   48 x 9
//   52 x 2
//   56 x 1
//   64 x 58
//   80 x 5
//   92 x 1
//   96 x 4
//   112 x 2
//   120 x 2
//   124 x 1
//   128 x 26
//   152 x 1
//   160 x 6
//   224 x 2
//   228 x 1
//   256 x 6
// 最大リピート回数: 4
// 最大リピート レベル: 1
// 2956 bytes

//----------------------------------------------------------------♩
//  Lead                    Base                    Chord0/1                          Drum             
static u8 const score0[] = {
    // -------- 小節2(t=0)
    SD6_L_FL(8, SD6_CS4),   SD6_B_FL(8, SD6_AS3),   SD6_C2_FL(24, SD6_CS3, SD6_AS2),  SD6_D_1(16),     
    SD6_L_FL(8, SD6_AS3),   SD6_B_FL(8, SD6_FS3),                                                      
    SD6_L_FL(8, SD6_FS3),   SD6_B_FL(8, SD6_DS3),                                     SD6_D_2(8),      
    SD6_L_FL(8, SD6_DS4),   SD6_B_FL(8, SD6_C4),    SD6_C2_FL(24, SD6_DS3, SD6_C3),   SD6_D_1(16),     
    SD6_L_FL(8, SD6_C4),    SD6_B_FL(8, SD6_GS3),                                                      
    SD6_L_FL(8, SD6_GS3),   SD6_B_FL(8, SD6_F3),                                      SD6_D_2(8),      
    SD6_L_FL(8, SD6_E4),    SD6_B_FL(8, SD6_CS4),   SD6_C2_FL(24, SD6_E3, SD6_CS3),   SD6_D_1(16),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_FL(8, SD6_A3),                                                       
    SD6_L_FL(8, SD6_A3),    SD6_B_FL(8, SD6_FS3),                                     SD6_D_2(8),      
    SD6_L_FL(8, SD6_FS4),   SD6_B_FL(8, SD6_DS4),   SD6_C2_FL(24, SD6_FS3, SD6_DS3),  SD6_D_1(16),     
    SD6_L_FL(8, SD6_DS4),   SD6_B_FL(8, SD6_B3),                                                       
    SD6_L_FL(8, SD6_B3),    SD6_B_FL(8, SD6_GS3),                                     SD6_D_2(8),      
    SD6_L_FL(32, SD6_F4),   SD6_B_FL(64, SD6_GS2),  SD6_C2_FL(64, SD6_F3, SD6_CS3),   SD6_D_1(256),    
    // -------- 小節3(t=128)
    SD6_L_DW(256, SD6_F4),  SD6_B_DW(224, SD6_GS2), SD6_C2_DW(224, SD6_F3, SD6_CS3),  
    // -------- 小節4(t=256)
                                                                                      SD6_D_REST(256), 
    // -------- 小節5(t=384)
    SD6_L_FL(48, SD6_B3),   SD6_B_DW(32, SD6_GS2),  SD6_C2_FL(128, SD6_DS3, SD6_B2),                   
                            SD6_B_DW(32, SD6_GS2),                                                     
    SD6_L_FL(8, SD6_AS3),                                                                              
    SD6_L_FL(48, SD6_B3),   SD6_B_DW(32, SD6_GS2),                                                     
                            SD6_B_DW(32, SD6_GS2),                                                     
    SD6_L_FL(8, SD6_CS4),                                                                              
    SD6_L_FL(16, SD6_DS4),  
    // -------- 小節6(t=512)
    SD6_L_FL(16, SD6_CS4),  SD6_B_DW(32, SD6_GS2),  SD6_C2_FL(64, SD6_DS3, SD6_B2),                    
    SD6_L_FL(16, SD6_B3),                                                                              
    SD6_L_FL(16, SD6_AS3),  SD6_B_DW(32, SD6_GS2),                                                     
    SD6_L_FL(16, SD6_FS3),                                                                             
    SD6_L_FL(64, SD6_GS3),  SD6_B_DW(32, SD6_GS2),  SD6_C2_UP(64, SD6_F3, SD6_CS3),                    
                            SD6_B_DW(32, SD6_GS2),                                    SD6_D_REST(256), 
    // -------- 小節7(t=640)
    SD6_L_FL(48, SD6_B3),   SD6_B_DW(32, SD6_GS2),  SD6_C2_FL(128, SD6_DS3, SD6_B2),                   
                            SD6_B_DW(32, SD6_GS2),                                                     
    SD6_L_FL(8, SD6_AS3),                                                                              
    SD6_L_FL(48, SD6_B3),   SD6_B_DW(32, SD6_GS2),                                                     
                            SD6_B_DW(32, SD6_GS2),                                                     
    SD6_L_FL(8, SD6_CS4),                                                                              
    SD6_L_FL(8, SD6_D4),                                                                               
    SD6_L_FL(8, SD6_DS4),   
    // -------- 小節8(t=768)
    SD6_L_FL(8, SD6_FS4),   SD6_B_DW(32, SD6_GS2),  SD6_C2_FL(64, SD6_DS3, SD6_B2),                    
    SD6_L_REP_3,                                                                                       
    SD6_L_FL(4, SD6_B3),                                                                               
    SD6_L_FL(4, SD6_D4),                                                                               
    SD6_L_ENDR,                                                                                        
    SD6_L_FL(4, SD6_B3),    SD6_B_DW(32, SD6_GS2),                                                     
    SD6_L_SLIDE_SPEED_R4,                                                                              
    SD6_L_FL(92, SD6_GS4),  SD6_B_DW(32, SD6_GS2),  SD6_C2_UP(64, SD6_F3, SD6_CS3),                    
                            SD6_B_DW(32, SD6_GS2),                                    SD6_D_REST(32),  
    // -------- 小節9(t=896)
    SD6_L_DW(8, SD6_FS4),   SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_D3, SD6_FS3),  SD6_D_1(32),     
    SD6_L_DW(8, SD6_E4),                                                                               
    SD6_L_DW(64, SD6_FS4),  SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
                            SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_DW(8, SD6_GS4),   SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_DW(8, SD6_A4),    SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
    SD6_L_DW(8, SD6_B4),    SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_DW(8, SD6_GS4),   SD6_B_DW(8, SD6_B2),                                      SD6_D_1(16),     
    SD6_L_DW(8, SD6_E4),    SD6_B_DW(16, SD6_B1),                                                      
    SD6_L_DW(8, SD6_GS4),                                                             SD6_D_3(8),      
    // -------- 小節10(t=1024)
    SD6_L_DW(8, SD6_FS4),   SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
    SD6_L_DW(8, SD6_E4),                                                                               
    SD6_L_DW(112, SD6_FS4), SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(16, SD6_B2),                                     SD6_D_1(16),     
                            SD6_B_DW(8, SD6_B2),                                                       
                            SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_2(16),     
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_1(8),      
                            SD6_B_DW(8, SD6_D2),                                      SD6_D_1(8),      
    // -------- 小節11(t=1152)
    SD6_L_DW(8, SD6_FS4),   SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_FS3, SD6_D3),  SD6_D_1(32),     
    SD6_L_DW(8, SD6_E4),                                                                               
    SD6_L_DW(64, SD6_FS4),  SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
                            SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_DW(8, SD6_GS4),   SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_DW(8, SD6_A4),    SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
    SD6_L_DW(8, SD6_B4),    SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_DW(8, SD6_GS4),   SD6_B_DW(8, SD6_B2),                                      SD6_D_1(24),     
    SD6_L_DW(8, SD6_E4),    SD6_B_DW(16, SD6_B1),                                                      
    SD6_L_DW(8, SD6_GS4),   
    // -------- 小節12(t=1280)
    SD6_L_DW(8, SD6_FS4),   SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
    SD6_L_DW(8, SD6_E4),                                                                               
    SD6_L_DW(112, SD6_FS4), SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(16, SD6_B2),                                     SD6_D_1(16),     
                            SD6_B_DW(8, SD6_B2),                                                       
                            SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_3(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(8, SD6_D2),    
    // -------- 小節13(t=1408)
    SD6_L_DW(8, SD6_FS4),   SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_FS3, SD6_D3),  SD6_D_1(32),     
    SD6_L_DW(8, SD6_E4),                                                                               
    SD6_L_DW(8, SD6_D4),                                                                               
    SD6_L_DW(8, SD6_CS4),                                                                              
    SD6_L_DW(8, SD6_D4),    SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
    SD6_L_DW(8, SD6_CS4),                                                                              
    SD6_L_DW(8, SD6_B3),                                                                               
    SD6_L_DW(8, SD6_A3),                                                                               
    SD6_L_DW(8, SD6_B3),    SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
    SD6_L_DW(8, SD6_A3),    SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_DW(8, SD6_FS3),   SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_DW(8, SD6_E3),    SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
    SD6_L_DW(160, SD6_FS3), SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_1(16),     
                            SD6_B_DW(16, SD6_B1),                                     SD6_D_3(8),      
    // -------- 小節14(t=1536)
                            SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(16, SD6_B2),                                     SD6_D_1(16),     
                            SD6_B_DW(8, SD6_B2),                                                       
                            SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_2(16),     
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_1(8),      
                            SD6_B_DW(8, SD6_D2),                                      SD6_D_1(8),      
    // -------- 小節15(t=1664)
    SD6_L_DW(8, SD6_FS3),   SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_FS3, SD6_D3),  SD6_D_1(32),     
    SD6_L_DW(8, SD6_E3),                                                                               
    SD6_L_DW(8, SD6_FS3),                                                                              
    SD6_L_DW(8, SD6_A3),                                                                               
    SD6_L_DW(8, SD6_B3),    SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
    SD6_L_DW(8, SD6_A3),                                                                               
    SD6_L_DW(8, SD6_B3),                                                                               
    SD6_L_DW(8, SD6_CS4),                                                                              
    SD6_L_DW(8, SD6_D4),    SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
    SD6_L_DW(8, SD6_CS4),   SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_DW(8, SD6_D4),    SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_DW(8, SD6_E4),    SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
    SD6_L_DW(160, SD6_FS4), SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_1(24),     
                            SD6_B_DW(16, SD6_B1),   
    // -------- 小節16(t=1792)
                            SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(16, SD6_B2),                                     SD6_D_1(16),     
                            SD6_B_DW(8, SD6_B2),                                                       
                            SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_3(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(8, SD6_D2),    
    // -------- 小節17(t=1920)
    SD6_L_DW(4, SD6_FS3),   SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_FS3, SD6_D3),  SD6_D_1(32),     
    SD6_L_DW(4, SD6_E3),                                                                               
    SD6_L_DW(4, SD6_FS3),                                                                              
    SD6_L_REP_2,                                                                                       
    SD6_L_DW(4, SD6_B3),                                                                               
    SD6_L_DW(4, SD6_E4),                                                                               
    SD6_L_ENDR,                                                                                        
    SD6_L_DW(4, SD6_FS4),                                                                              
    SD6_L_DW(4, SD6_E4),    SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
    SD6_L_DW(4, SD6_B3),                                                                               
    SD6_L_DW(4, SD6_FS3),                                                                              
    SD6_L_DW(4, SD6_E3),                                                                               
    SD6_L_DW(4, SD6_CS3),                                                                              
    SD6_L_DW(4, SD6_E3),                                                                               
    SD6_L_DW(4, SD6_FS3),                                                                              
    SD6_L_DW(4, SD6_B3),                                                                               
    SD6_L_DW(4, SD6_E4),    SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
    SD6_L_DW(4, SD6_B3),                                                                               
    SD6_L_DW(4, SD6_E4),    SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_DW(4, SD6_FS4),                                                                              
    SD6_L_DW(4, SD6_E4),    SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_DW(4, SD6_B3),                                                                               
    SD6_L_DW(4, SD6_FS3),   SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
    SD6_L_DW(4, SD6_E3),                                                                               
    SD6_L_DW(4, SD6_CS3),   SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_DW(4, SD6_E3),                                                                               
    SD6_L_DW(152, SD6_FS3), SD6_B_DW(8, SD6_B2),                                      SD6_D_1(16),     
                            SD6_B_DW(16, SD6_B1),                                     SD6_D_3(8),      
    // -------- 小節18(t=2048)
                            SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(16, SD6_B2),                                     SD6_D_1(16),     
                            SD6_B_DW(8, SD6_B2),                                                       
                            SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_2(16),     
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_1(8),      
                            SD6_B_DW(8, SD6_D2),                                      SD6_D_1(8),      
    // -------- 小節19(t=2176)
    SD6_L_SLIDE_OFF,                                                                                   
    SD6_L_FL(4, SD6_FS3),   SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_FS3, SD6_D3),  SD6_D_1(32),     
    SD6_L_SLIDE_SPEED_R4,                                                                              
    SD6_L_FL(228, SD6_GS4), SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_1(24),     
                            SD6_B_DW(16, SD6_B1),   
    // -------- 小節20(t=2304)
                            SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(16, SD6_B2),                                     SD6_D_1(16),     
                            SD6_B_DW(8, SD6_B2),                                                       
                            SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_3(8),      
    SD6_L_DW(8, SD6_GS4),   SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_DW(8, SD6_E4),    SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
    SD6_L_DW(8, SD6_CS4),   SD6_B_DW(8, SD6_D2),    
    // -------- 小節21(t=2432)
    SD6_L_DW(8, SD6_E4),    SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_FS3, SD6_D3),  SD6_D_1(32),     
    SD6_L_DW(96, SD6_FS4),  SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_DW(8, SD6_GS4),   SD6_B_DW(8, SD6_B2),                                      SD6_D_1(16),     
    SD6_L_DW(8, SD6_E4),    SD6_B_DW(16, SD6_B1),                                                      
    SD6_L_DW(8, SD6_CS4),                                                             SD6_D_3(8),      
    // -------- 小節22(t=2560)
    SD6_L_DW(8, SD6_E4),    SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
    SD6_L_DW(96, SD6_FS4),  SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(16, SD6_B2),                                     SD6_D_1(16),     
                            SD6_B_DW(8, SD6_B2),                                                       
                            SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_2(16),     
    SD6_L_DW(8, SD6_GS4),   SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_DW(8, SD6_E4),    SD6_B_DW(8, SD6_B2),                                      SD6_D_1(8),      
    SD6_L_DW(8, SD6_CS4),   SD6_B_DW(8, SD6_D2),                                      SD6_D_1(8),      
    // -------- 小節23(t=2688)
    SD6_L_DW(8, SD6_E4),    SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_FS3, SD6_D3),  SD6_D_1(32),     
    SD6_L_DW(96, SD6_FS4),  SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_DW(8, SD6_GS4),   SD6_B_DW(8, SD6_B2),                                      SD6_D_1(24),     
    SD6_L_DW(8, SD6_E4),    SD6_B_DW(16, SD6_B1),                                                      
    SD6_L_DW(8, SD6_CS4),   
    // -------- 小節24(t=2816)
    SD6_L_DW(8, SD6_E4),    SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
    SD6_L_DW(96, SD6_FS4),  SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(16, SD6_B2),                                     SD6_D_1(16),     
                            SD6_B_DW(8, SD6_B2),                                                       
                            SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_3(8),      
    SD6_L_DW(8, SD6_GS4),   SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_DW(8, SD6_E4),    SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
    SD6_L_DW(8, SD6_CS4),   SD6_B_DW(8, SD6_D2),    
    // -------- 小節25(t=2944)
    SD6_L_DW(8, SD6_E4),    SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_FS3, SD6_D3),  SD6_D_1(32),     
    SD6_L_DW(56, SD6_FS4),  SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
    SD6_L_DW(4, SD6_FS3),   SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
    SD6_L_DW(4, SD6_B3),                                                                               
    SD6_L_DW(4, SD6_CS4),   SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_DW(4, SD6_B3),                                                                               
    SD6_L_DW(4, SD6_CS4),   SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_DW(4, SD6_B3),                                                                               
    SD6_L_DW(4, SD6_FS3),   SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
    SD6_L_DW(4, SD6_CS3),                                                                              
    SD6_L_DW(4, SD6_FS3),   SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_DW(4, SD6_B3),                                                                               
    SD6_L_DW(4, SD6_CS4),   SD6_B_DW(8, SD6_B2),                                      SD6_D_1(16),     
    SD6_L_DW(4, SD6_B3),                                                                               
    SD6_L_DW(4, SD6_CS4),   SD6_B_DW(16, SD6_B1),                                                      
    SD6_L_DW(4, SD6_B3),                                                                               
    SD6_L_DW(4, SD6_FS3),                                                             SD6_D_3(8),      
    SD6_L_DW(4, SD6_CS3),   
    // -------- 小節26(t=3072)
    SD6_L_DW(80, SD6_FS3),  SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(16, SD6_B2),                                     SD6_D_1(16),     
                            SD6_B_DW(8, SD6_B2),                                                       
                            SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_E2),                                                       
    SD6_L_ENV_SPEED_R4,                                                                                
    SD6_L_UP(48, SD6_FS4),  SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_2(16),     
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_1(8),      
                            SD6_B_DW(8, SD6_D2),                                      SD6_D_1(8),      
    // -------- 小節27(t=3200)
    SD6_L_SLIDE_OFF,                                                                                   
    SD6_L_FL(32, SD6_FS4),  SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_FS3, SD6_D3),  SD6_D_1(32),     
    SD6_L_SLIDE_SPEED_R1,                                                                              
    SD6_L_FL(32, SD6_E4),   SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
    SD6_L_FL(32, SD6_FS4),  SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
    SD6_L_FL(32, SD6_A4),   SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_1(24),     
                            SD6_B_DW(16, SD6_B1),   
    // -------- 小節28(t=3328)
    SD6_L_FL(32, SD6_FS4),  SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(32, SD6_E4),   SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(16, SD6_B2),                                     SD6_D_1(16),     
                            SD6_B_DW(8, SD6_B2),                                                       
    SD6_L_FL(32, SD6_D4),   SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_E2),                                                       
    SD6_L_FL(32, SD6_CS4),  SD6_B_DW(8, SD6_FS2),                                     SD6_D_3(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(8, SD6_D2),    
    // -------- 小節29(t=3456)
    SD6_L_FL(64, SD6_B3),   SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_FS3, SD6_D3),  SD6_D_1(32),     
                            SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
    SD6_L_FL(32, SD6_A3),   SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
    SD6_L_SLIDE_SPEED_R4,                                                                              
    SD6_L_FL(32, SD6_B3),   SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_1(16),     
                            SD6_B_DW(16, SD6_B1),                                     SD6_D_3(8),      
    // -------- 小節30(t=3584)
    SD6_L_SLIDE_OFF,                                                                                   
    SD6_L_FL(64, SD6_B3),   SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(16, SD6_B2),                                     SD6_D_1(16),     
                            SD6_B_DW(8, SD6_B2),                                                       
    SD6_L_SLIDE_SPEED_R1,                                                                              
    SD6_L_FL(64, SD6_FS3),  SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_2(16),     
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_1(8),      
                            SD6_B_DW(8, SD6_D2),                                      SD6_D_1(8),      
    // -------- 小節31(t=3712)
    SD6_L_SLIDE_OFF,                                                                                   
    SD6_L_FL(32, SD6_FS4),  SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_FS3, SD6_D3),  SD6_D_1(32),     
    SD6_L_SLIDE_SPEED_R1,                                                                              
    SD6_L_FL(32, SD6_E4),   SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
    SD6_L_FL(32, SD6_FS4),  SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
    SD6_L_FL(32, SD6_A4),   SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_1(24),     
                            SD6_B_DW(16, SD6_B1),   
    // -------- 小節32(t=3840)
    SD6_L_FL(32, SD6_FS4),  SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(32, SD6_E4),   SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(16, SD6_B2),                                     SD6_D_1(16),     
                            SD6_B_DW(8, SD6_B2),                                                       
    SD6_L_FL(32, SD6_D4),   SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_E2),                                                       
    SD6_L_FL(32, SD6_CS4),  SD6_B_DW(8, SD6_FS2),                                     SD6_D_3(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(8, SD6_D2),    
    // -------- 小節33(t=3968)
    SD6_L_SLIDE_OFF,                                                                                   
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_FS3, SD6_D3),  SD6_D_1(32),     
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),                                                                              
    SD6_L_FL(8, SD6_CS4),                                                                              
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
    SD6_L_FL(8, SD6_FS3),                                                                              
    SD6_L_FL(8, SD6_D4),                                                                               
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_B2),                                      SD6_D_1(16),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(16, SD6_B1),                                                      
    SD6_L_FL(8, SD6_A3),                                                              SD6_D_3(8),      
    // -------- 小節34(t=4096)
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS4),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(8, SD6_CS4),                                                                              
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(8, SD6_D4),                                                              SD6_D_1(16),     
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_B2),                                                       
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_E2),                                                       
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_E2),                                                       
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(8, SD6_FS2),                                     SD6_D_2(16),     
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_B2),                                      SD6_D_1(8),      
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_D2),                                      SD6_D_1(8),      
    // -------- 小節35(t=4224)
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_FS3, SD6_D3),  SD6_D_1(32),     
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),                                                                              
    SD6_L_FL(8, SD6_CS4),                                                                              
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
    SD6_L_FL(8, SD6_FS3),                                                                              
    SD6_L_FL(8, SD6_D4),                                                                               
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_B2),                                      SD6_D_1(24),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(16, SD6_B1),                                                      
    SD6_L_FL(8, SD6_A3),    
    // -------- 小節36(t=4352)
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS4),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(8, SD6_CS4),                                                                              
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(8, SD6_D4),                                                              SD6_D_1(16),     
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_B2),                                                       
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_E2),                                                       
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_E2),                                                       
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(8, SD6_FS2),                                     SD6_D_3(8),      
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_D2),    
    // -------- 小節37(t=4480)
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_FS3, SD6_D3),  SD6_D_1(32),     
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),                                                                              
    SD6_L_FL(8, SD6_CS4),                                                                              
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
    SD6_L_FL(8, SD6_FS3),                                                                              
    SD6_L_FL(8, SD6_D4),                                                                               
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_B2),                                      SD6_D_1(16),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(16, SD6_B1),                                                      
    SD6_L_FL(8, SD6_A3),                                                              SD6_D_3(8),      
    // -------- 小節38(t=4608)
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(8, SD6_CS4),                                                                              
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(8, SD6_D4),                                                              SD6_D_1(16),     
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_B2),                                                       
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_E2),                                                       
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_E2),                                                       
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(8, SD6_FS2),                                     SD6_D_2(16),     
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_B2),                                      SD6_D_1(8),      
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_D2),                                      SD6_D_1(8),      
    // -------- 小節39(t=4736)
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_FS3, SD6_D3),  SD6_D_1(32),     
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),                                                                              
    SD6_L_FL(8, SD6_CS4),                                                                              
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
    SD6_L_FL(8, SD6_FS3),                                                                              
    SD6_L_FL(8, SD6_D4),                                                                               
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_B2),                                      SD6_D_1(24),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(16, SD6_B1),                                                      
    SD6_L_FL(8, SD6_A3),    
    // -------- 小節40(t=4864)
    SD6_L_REP_2,                                                                                       
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(8, SD6_CS4),                                                                              
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(8, SD6_D4),                                                              SD6_D_1(16),     
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_B2),                                                       
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_E2),                                                       
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_E2),                                                       
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(8, SD6_FS2),                                     SD6_D_3(8),      
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_D2),    
    // -------- 小節41(t=4992)
    SD6_L_FL(8, SD6_DS4),   SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_DS3, SD6_FS3), SD6_D_1(32),     
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),                                                                              
    SD6_L_FL(8, SD6_CS4),                                                                              
    SD6_L_FL(8, SD6_AS3),   SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
    SD6_L_FL(8, SD6_FS3),                                                                              
    SD6_L_FL(8, SD6_DS4),                                                                              
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_FL(8, SD6_AS3),   SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
    SD6_L_FL(8, SD6_DS4),   SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_B2),                                      SD6_D_1(16),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(16, SD6_B1),                                                      
    SD6_L_FL(8, SD6_AS3),                                                             SD6_D_3(8),      
    // -------- 小節42(t=5120)
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(8, SD6_CS4),                                                                              
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(8, SD6_D4),                                                              SD6_D_1(16),     
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_B2),                                                       
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_E2),                                                       
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_E2),                                                       
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(8, SD6_FS2),                                     SD6_D_2(16),     
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_B2),                                      SD6_D_1(8),      
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_D2),                                      SD6_D_1(8),      
    // -------- 小節43(t=5248)
    SD6_L_FL(8, SD6_DS4),   SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_DS3, SD6_FS3), SD6_D_1(32),     
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),                                                                              
    SD6_L_FL(8, SD6_CS4),                                                                              
    SD6_L_FL(8, SD6_AS3),   SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
    SD6_L_FL(8, SD6_FS3),                                                                              
    SD6_L_FL(8, SD6_DS4),                                                                              
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_FL(8, SD6_AS3),   SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
    SD6_L_FL(8, SD6_DS4),   SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_B2),                                      SD6_D_1(24),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(16, SD6_B1),                                                      
    SD6_L_FL(8, SD6_AS3),                                                                              
    SD6_L_ENDR,             
    // -------- 小節48(t=5888)
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(8, SD6_CS4),                                                                              
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(8, SD6_D4),                                                              SD6_D_1(16),     
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_B2),                                                       
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_E2),                                                       
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_FS2),                                                      
    SD6_L_FL(8, SD6_FS3),   SD6_B_DW(8, SD6_E2),                                                       
    SD6_L_FL(8, SD6_D4),    SD6_B_DW(8, SD6_FS2),                                     SD6_D_3(8),      
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_D2),    
    // -------- 小節49(t=6016)
    SD6_L_REP_2,                                                                                       
    SD6_L_DW(120, SD6_DS4), SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_DS3, SD6_FS3), SD6_D_1(32),     
                            SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_1(16),     
                            SD6_B_DW(16, SD6_B1),                                                      
    SD6_L_DW(8, SD6_E4),                                                              SD6_D_3(8),      
    // -------- 小節50(t=6144)
    SD6_L_DW(64, SD6_D4),   SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(16, SD6_B2),                                     SD6_D_1(16),     
                            SD6_B_DW(8, SD6_B2),                                                       
    SD6_L_DW(4, SD6_FS4),   SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
    SD6_L_DW(52, SD6_E4),   SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_2(16),     
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_1(8),      
    SD6_L_DW(8, SD6_FS4),   SD6_B_DW(8, SD6_D2),                                      SD6_D_1(8),      
    // -------- 小節51(t=6272)
    SD6_L_DW(120, SD6_DS4), SD6_B_DW(32, SD6_B1),   SD6_C2_DW(128, SD6_DS3, SD6_FS3), SD6_D_1(32),     
                            SD6_B_DW(32, SD6_B2),                                     SD6_D_2(32),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(24),     
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_1(24),     
                            SD6_B_DW(16, SD6_B1),                                                      
    SD6_L_DW(8, SD6_E4),    
    // -------- 小節52(t=6400)
    SD6_L_DW(64, SD6_D4),   SD6_B_DW(16, SD6_B1),   SD6_C2_DW(64, SD6_FS3, SD6_D3),   SD6_D_1(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
                            SD6_B_DW(16, SD6_B2),                                     SD6_D_1(16),     
                            SD6_B_DW(8, SD6_B2),                                                       
    SD6_L_DW(4, SD6_FS4),   SD6_B_DW(8, SD6_A2),    SD6_C2_UP(64, SD6_GS3, SD6_E3),   SD6_D_1(32),     
    SD6_L_DW(52, SD6_E4),   SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_E2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_3(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_2(8),      
                            SD6_B_DW(8, SD6_B2),                                      SD6_D_2(16),     
    SD6_L_DW(8, SD6_FS4),   SD6_B_DW(8, SD6_D2),                                                       
                            SD6_L_ENDR,             
    // -------- 小節57(t=7040)
    SD6_L_ENV_SPEED_R16,                                                                               
    SD6_L_UP(256, SD6_B4),  SD6_B_DW(32, SD6_B1),   SD6_C2_DW(32, SD6_B3, SD6_DS3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_A2),    SD6_C2_DW(32, SD6_FS3, SD6_B3),   SD6_D_3(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_A3, SD6_E3),    SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
                            SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_GS3, SD6_E3),   SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
                            SD6_B_DW(8, SD6_FS2),   SD6_C2_DW(16, SD6_A3, SD6_E3),    SD6_D_2(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_1(8),      
    // -------- 小節58(t=7168)
                            SD6_B_DW(32, SD6_B1),   SD6_C2_DW(32, SD6_B3, SD6_DS3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_A2),    SD6_C2_DW(32, SD6_FS3, SD6_B3),   SD6_D_3(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_A3, SD6_E3),    SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
                            SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_GS3, SD6_E3),   SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
                            SD6_B_DW(8, SD6_FS2),   SD6_C2_DW(16, SD6_A3, SD6_E3),    SD6_D_2(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_1(8),      
    // -------- 小節59(t=7296)
    SD6_L_SLIDE_SPEED_R1,                                                                              
    SD6_L_FL(256, SD6_B4),  SD6_B_DW(32, SD6_B1),   SD6_C2_DW(32, SD6_B3, SD6_DS3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_A2),    SD6_C2_DW(32, SD6_FS3, SD6_B3),   SD6_D_3(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_A3, SD6_E3),    SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
                            SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_GS3, SD6_E3),   SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
                            SD6_B_DW(8, SD6_FS2),   SD6_C2_DW(16, SD6_A3, SD6_E3),    SD6_D_2(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_1(8),      
    // -------- 小節60(t=7424)
                            SD6_B_DW(32, SD6_B1),   SD6_C2_DW(32, SD6_B3, SD6_DS3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_A2),    SD6_C2_DW(32, SD6_FS3, SD6_B3),   SD6_D_3(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_A3, SD6_E3),    SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
                            SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_GS3, SD6_E3),   SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
                            SD6_B_DW(8, SD6_FS2),   SD6_C2_DW(16, SD6_A3, SD6_E3),    SD6_D_2(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_1(8),      
    // -------- 小節61(t=7552)
    SD6_L_REP_2,                                                                                       
    SD6_L_SLIDE_OFF,                                                                                   
    SD6_L_FL(16, SD6_B4),   SD6_B_DW(32, SD6_B1),   SD6_C2_DW(32, SD6_B3, SD6_DS3),   SD6_D_1(32),     
    SD6_L_FL(16, SD6_CS5),                                                                             
    SD6_L_FL(8, SD6_AS4),   SD6_B_DW(8, SD6_A2),    SD6_C2_DW(32, SD6_FS3, SD6_B3),   SD6_D_3(32),     
    SD6_L_FL(8, SD6_GS4),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(16, SD6_FS4),  SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_FL(16, SD6_A4),   SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_A3, SD6_E3),    SD6_D_2(16),     
    SD6_L_FL(16, SD6_B4),   SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
                            SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_GS3, SD6_E3),   SD6_D_2(16),     
    SD6_L_FL(8, SD6_GS4),                                                                              
    SD6_L_FL(8, SD6_FS4),   SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
    SD6_L_FL(16, SD6_E4),   SD6_B_DW(8, SD6_FS2),   SD6_C2_DW(16, SD6_A3, SD6_E3),    SD6_D_2(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_1(8),      
    // -------- 小節62(t=7680)
    SD6_L_DW(128, SD6_FS4), SD6_B_DW(32, SD6_B1),   SD6_C2_DW(32, SD6_B3, SD6_DS3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_A2),    SD6_C2_DW(32, SD6_FS3, SD6_B3),   SD6_D_3(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_A3, SD6_E3),    SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
                            SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_GS3, SD6_E3),   SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
                            SD6_B_DW(8, SD6_FS2),   SD6_C2_DW(16, SD6_A3, SD6_E3),    SD6_D_2(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_1(8),      
                                                                                      SD6_L_ENDR,      
    // -------- 小節65(t=8064)
    SD6_L_REP_4,                                                                                       
    SD6_L_DW(32, SD6_B4),   SD6_B_DW(32, SD6_B1),   SD6_C2_DW(32, SD6_B3, SD6_DS3),   SD6_D_1(32),     
    SD6_L_DW(32, SD6_AS4),  SD6_B_DW(8, SD6_A2),    SD6_C2_DW(32, SD6_FS3, SD6_B3),   SD6_D_3(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_DW(24, SD6_A4),   SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_A3, SD6_E3),    SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
    SD6_L_DW(24, SD6_GS4),  SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_GS3, SD6_E3),   SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
    SD6_L_DW(16, SD6_A4),   SD6_B_DW(8, SD6_FS2),   SD6_C2_DW(16, SD6_A3, SD6_E3),    SD6_D_2(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_1(8),      
                                                                                      SD6_L_ENDR,      
    // -------- 小節69(t=8576)
    SD6_L_REP_2,                                                                                       
    SD6_L_FL(16, SD6_B4),   SD6_B_DW(32, SD6_B1),   SD6_C2_DW(32, SD6_B3, SD6_DS3),   SD6_D_1(32),     
    SD6_L_FL(16, SD6_CS5),                                                                             
    SD6_L_FL(8, SD6_AS4),   SD6_B_DW(8, SD6_A2),    SD6_C2_DW(32, SD6_FS3, SD6_B3),   SD6_D_3(32),     
    SD6_L_FL(8, SD6_GS4),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(8, SD6_FS4),                                                                              
    SD6_L_FL(8, SD6_GS4),   SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_FL(8, SD6_A4),    SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_A3, SD6_E3),    SD6_D_2(16),     
    SD6_L_FL(8, SD6_GS4),                                                                              
    SD6_L_FL(8, SD6_FS4),   SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
    SD6_L_FL(8, SD6_E4),    SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_GS3, SD6_E3),   SD6_D_2(16),     
    SD6_L_FL(8, SD6_GS4),                                                                              
    SD6_L_FL(8, SD6_FS4),   SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
    SD6_L_FL(8, SD6_E4),    SD6_B_DW(8, SD6_FS2),   SD6_C2_DW(16, SD6_A3, SD6_E3),    SD6_D_2(8),      
    SD6_L_FL(8, SD6_FS4),   SD6_B_DW(8, SD6_A2),                                      SD6_D_1(8),      
    // -------- 小節70(t=8704)
    SD6_L_DW(128, SD6_DS4), SD6_B_DW(32, SD6_B1),   SD6_C2_DW(32, SD6_B3, SD6_DS3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_A2),    SD6_C2_DW(32, SD6_FS3, SD6_B3),   SD6_D_3(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_A3, SD6_E3),    SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
                            SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_GS3, SD6_E3),   SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
                            SD6_B_DW(8, SD6_FS2),   SD6_C2_DW(16, SD6_A3, SD6_E3),    SD6_D_2(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_1(8),      
                                                                                      SD6_L_ENDR,      
    // -------- 小節73(t=9088)
    SD6_L_REP_2,                                                                                       
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(32, SD6_B1),   SD6_C2_DW(32, SD6_B3, SD6_DS3),   SD6_D_1(32),     
    SD6_L_FL(8, SD6_CS4),                                                                              
    SD6_L_FL(8, SD6_DS4),                                                                              
    SD6_L_FL(8, SD6_E4),                                                                               
    SD6_L_FL(8, SD6_FS4),   SD6_B_DW(8, SD6_A2),    SD6_C2_DW(32, SD6_FS3, SD6_B3),   SD6_D_3(32),     
    SD6_L_FL(8, SD6_GS4),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(8, SD6_A4),                                                                               
    SD6_L_FL(8, SD6_GS4),   SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_FL(8, SD6_A4),    SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_A3, SD6_E3),    SD6_D_2(16),     
    SD6_L_FL(8, SD6_GS4),                                                                              
    SD6_L_FL(8, SD6_FS4),   SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
    SD6_L_FL(8, SD6_E4),    SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_GS3, SD6_E3),   SD6_D_2(16),     
    SD6_L_FL(8, SD6_GS4),                                                                              
    SD6_L_FL(8, SD6_FS4),   SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
    SD6_L_FL(8, SD6_E4),    SD6_B_DW(8, SD6_FS2),   SD6_C2_DW(16, SD6_A3, SD6_E3),    SD6_D_2(8),      
    SD6_L_FL(8, SD6_FS4),   SD6_B_DW(8, SD6_A2),                                      SD6_D_1(8),      
    // -------- 小節74(t=9216)
    SD6_L_DW(128, SD6_DS4), SD6_B_DW(32, SD6_B1),   SD6_C2_DW(32, SD6_B3, SD6_DS3),   SD6_D_1(32),     
                            SD6_B_DW(8, SD6_A2),    SD6_C2_DW(32, SD6_FS3, SD6_B3),   SD6_D_3(32),     
                            SD6_B_DW(16, SD6_B2),                                                      
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_A3, SD6_E3),    SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
                            SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_GS3, SD6_E3),   SD6_D_2(16),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
                            SD6_B_DW(8, SD6_FS2),   SD6_C2_DW(16, SD6_A3, SD6_E3),    SD6_D_2(8),      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_1(8),      
                                                                                      SD6_L_ENDR,      
    // -------- 小節77(t=9600)
    SD6_L_REP_4,                                                                                       
    SD6_L_FL(8, SD6_DS4),   SD6_B_DW(32, SD6_B1),   SD6_C2_DW(32, SD6_B3, SD6_DS3),   SD6_D_1(32),     
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_FS3),                                                                              
    SD6_L_FL(8, SD6_B3),                                                                               
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_A2),    SD6_C2_DW(32, SD6_FS3, SD6_B3),   SD6_D_3(32),     
    SD6_L_FL(8, SD6_AS3),   SD6_B_DW(16, SD6_B2),                                                      
    SD6_L_FL(8, SD6_FS3),                                                                              
    SD6_L_FL(8, SD6_AS3),   SD6_B_DW(8, SD6_A2),                                                       
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_A3, SD6_E3),    SD6_D_2(16),     
    SD6_L_FL(8, SD6_A3),                                                                               
    SD6_L_FL(8, SD6_E3),    SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
    SD6_L_FL(8, SD6_B3),    SD6_B_DW(16, SD6_FS2),  SD6_C2_DW(24, SD6_GS3, SD6_E3),   SD6_D_2(16),     
    SD6_L_FL(8, SD6_GS3),                                                                              
    SD6_L_FL(8, SD6_E3),    SD6_B_DW(8, SD6_E2),                                      SD6_D_1(8),      
    SD6_L_FL(8, SD6_CS4),   SD6_B_DW(8, SD6_FS2),   SD6_C2_DW(16, SD6_A3, SD6_E3),    SD6_D_2(8),      
    SD6_L_FL(8, SD6_A3),    SD6_B_DW(8, SD6_A2),                                      SD6_D_1(8),      
                                                                                      SD6_L_ENDR,      
    // -------- 小節81(t=10112)
    SD6_L_ENV_SPEED_R8,                                                                                
    SD6_L_UP(48, SD6_B4),   SD6_B_UP(48, SD6_B2),   SD6_C2_DW(48, SD6_DS3, SD6_FS3),  SD6_D_1(48),     
    SD6_L_UP(64, SD6_AS4),  SD6_B_UP(64, SD6_AS2),  SD6_C2_DW(64, SD6_D3, SD6_F3),    SD6_D_1(64),     
    SD6_L_UP(80, SD6_A4),   SD6_B_UP(80, SD6_A2),   SD6_C2_DW(80, SD6_E3, SD6_CS3),   SD6_D_1(80),     
    // -------- 小節82(t=10240)
    SD6_L_UP(160, SD6_GS4), SD6_B_UP(160, SD6_GS2), SD6_C2_DW(160, SD6_DS3, SD6_C3),  SD6_D_1(160),    
    // -------- 小節83(t=10368)
    SD6_L_FL(4, SD6_E3),    SD6_B_DW(32, SD6_B1),   SD6_C2_REST(128),                 SD6_D_1(32),     
    SD6_L_SLIDE_SPEED_R1,                                                                              
    SD6_L_FL(124, SD6_B2),  
    // -------- 小節84(t=10496)
                            SD6_B_DW(32, SD6_FS2),                                    SD6_D_3(32),     
                            SD6_B_DW(8, SD6_E2),                                      SD6_D_2(16),     
                            SD6_B_DW(8, SD6_FS2),                                                      
                            SD6_B_DW(8, SD6_A2),                                      SD6_D_1(8),      
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_2(16),     
                            SD6_B_DW(8, SD6_A2),                                                       
                            SD6_B_DW(8, SD6_FS2),                                     SD6_D_1(8),      
                            SD6_B_DW(8, SD6_D2),                                      SD6_D_2(8),      
                            SD6_B_DW(8, SD6_CS2),                                     SD6_D_1(8),      
    SD6_L_SLIDE_OFF,                                                                                   
    SD6_L_FL(16, SD6_B3),   SD6_B_DW(16, SD6_B1),   SD6_C2_DW(16, SD6_FS3, SD6_DS3),  SD6_D_1(16),     
    SD6_L_END
};
